language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > ./docker-compose
- chmod +x docker-compose
- mv ./docker-compose /usr/bin/docker-compose
- chmod +x /usr/bin/docker-compose
- docker login -u coca1719 -p coca1719
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t coca1719/se234-lab10-backend
  .
- docker push coca1719/se234-lab10-backend
- docker pull coca1719/se234-lab10-client
script:
- docker version
- docker-compose -H "$DOCKER_HOST" up -d
cache:
  directories:
  - "$HOME/.m2"